# Generated by Django 3.1.7 on 2021-04-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('registeredAt', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(default='kash', on_delete=django.db.models.deletion.CASCADE, to='agenda.users'),
        ),
    ]
