# Generated by Django 3.1.7 on 2021-04-20 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='ayes',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='nays',
        ),
        migrations.CreateModel(
            name='Nay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=255)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.users')),
            ],
        ),
        migrations.CreateModel(
            name='Aye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=255)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.users')),
            ],
        ),
    ]
