# Generated by Django 3.1.7 on 2021-04-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20210406_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='likes',
        ),
    ]
