# Generated by Django 3.1.7 on 2021-04-06 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20210406_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredAt', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.users')),
            ],
        ),
        migrations.CreateModel(
            name='Aye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredAt', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.users')),
            ],
        ),
    ]
