# Generated by Django 3.1.7 on 2021-04-06 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20210406_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aye',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda'),
        ),
        migrations.AlterField(
            model_name='nay',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda'),
        ),
    ]
