# Generated by Django 3.1.7 on 2021-04-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20210406_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nay',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='nay',
            name='user',
        ),
        migrations.AddField(
            model_name='agenda',
            name='ayes',
            field=models.ManyToManyField(related_name='agenda_aye', to='agenda.Users'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='nays',
            field=models.ManyToManyField(related_name='agenda_nay', to='agenda.Users'),
        ),
        migrations.DeleteModel(
            name='Aye',
        ),
        migrations.DeleteModel(
            name='Nay',
        ),
    ]
