# Generated by Django 3.1.7 on 2021-04-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20210406_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='slug',
            field=models.SlugField(default='default', editable='False', max_length=100),
        ),
    ]
